[package]
name = "bitcask"
version = "0.1.0"
edition = "2024"

[lib]
name="bitcask"

[dependencies]
anyhow = "1.0.100"
bincode = "2.0.1"
crc32fast = "1.5.0"
# flate2 = "1.0" # We will use it if we support compression in the future (it's compatible with bincode)
